# Generated by Django 4.2 on 2023-04-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_post_dislikes_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='uploads/profile_picture/default.jpg', upload_to='uploads/profile_pictures'),
        ),
    ]
