# Generated by Django 4.2 on 2023-04-19 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_child_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Child_comment',
        ),
    ]
