# Generated by Django 4.2 on 2023-04-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_alter_userprofile_picture_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, upload_to='uploads/post_photos'),
        ),
    ]
